In [1]:
import pandas as pd

In [2]:
web_url='https://en.wikipedia.org/wiki/Sachin_Tendulkar'

In [3]:
df1=pd.read_html(web_url)

In [5]:
len(df1)

39

In [6]:
df1[0]

,0,1,2,3,4
0,Tendulkar in 2015,Tendulkar in 2015,NaN,NaN,NaN
1,Personal information,Personal information,NaN,NaN,NaN
2,Full name,Sachin Ramesh Tendulkar,NaN,NaN,NaN
3,Born,"(age 49)Bombay, Maharashtra, India",NaN,NaN,NaN
4,Nickname,".mw-parser-output .hlist dl,.mw-parser-output ...",NaN,NaN,NaN
5,Height,165 cm (5 ft 5 in),NaN,NaN,NaN
6,Batting,Right-handed,NaN,NaN,NaN
7,Bowling,".mw-parser-output .plainlist ol,.mw-parser-out...",NaN,NaN,NaN
8,Role,Batting All-rounder,NaN,NaN,NaN
9,Relations,Arjun Tendulkar (son)Ramesh Tendulkar (father),NaN,NaN,NaN
10,Website,sachintendulkar.com,NaN,NaN,NaN
11,International information,International information,NaN,NaN,NaN
12,National side,India (1989–2013),NaN,NaN,NaN
13,Test debut (cap 187),15 November 1989 v Pakistan,NaN,NaN,NaN
14,Last Test,14 November 2013 v West Indies,NaN,NaN,NaN
15,ODI debut (cap 74),18 December 1989 v Pakistan,NaN,NaN,NaN
16,Last ODI,18 March 2012 v Pakistan,NaN,NaN,NaN
17,ODI shirt no.,"10 (formerly 99, 33)",NaN,NaN,NaN
18,Only T20I (cap 11),1 December 2006 v South Africa,NaN,NaN,NaN
19,Domestic team information,Domestic team information,NaN,NaN,NaN
20,Years,Team,NaN,NaN,NaN
21,1988–2013,Mumbai,NaN,NaN,NaN
22,1992,Yorkshire,NaN,NaN,NaN
23,1994,East Bengal[3],NaN,NaN,NaN
24,2008–2013,Mumbai Indians (squad no. 10),NaN,NaN,NaN
25,Career statistics,Career statistics,NaN,NaN,NaN
26,Competition Test ODI FC LA Matches 200 463 310...,Competition Test ODI FC LA Matches 200 463 310...,NaN,NaN,NaN
27,Competition,Test,ODI,FC,LA
28,Matches,200,463,310,551
29,Runs scored,15921,18426,25396,21999
30,Batting average,53.78,44.83,57.84,45.54
31,100s/50s,51/68,49/96,81/116,60/114
32,Top score,248*,200*,248*,200*
33,Balls bowled,4240,8054,7605,10230
34,Wickets,46,154,71,201
35,Bowling average,54.17,44.48,61.74,42.17
36,5 wickets in innings,0,2,0,2
37,10 wickets in match,0,0,0,0
38,Best bowling,3/10,5/32,3/10,5/32
39,Catches/stumpings,115/–,140/–,186/–,175/–
40,Medal record Men's Cricket Representing India...,Medal record Men's Cricket Representing India...,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN
42,Men's Cricket,Men's Cricket,Men's Cricket,NaN,NaN
43,Representing India,Representing India,Representing India,NaN,NaN
44,World Cup,World Cup,World Cup,NaN,NaN
45,Winner,2011 India–Bangladesh–Sri Lanka,NaN,NaN,NaN
46,Runner-up,2003 South Africa–Zimbabwe–Kenya,NaN,NaN,NaN
47,"Source: ESPNcricinfo, 15 November 2013","Source: ESPNcricinfo, 15 November 2013",NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN
50,"Member of Parliament, Rajya Sabha","Member of Parliament, Rajya Sabha",NaN,NaN,NaN
51,In office27 April 2012 – 26 April 2018,In office27 April 2012 – 26 April 2018,NaN,NaN,NaN
52,Constituency,Nominated,NaN,NaN,NaN
53,Signature,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN

In [7]:
df1[30]

,vteIndia squad – 1992 Cricket World Cup,vteIndia squad – 1992 Cricket World Cup.1,vteIndia squad – 1992 Cricket World Cup.2
0,1 Azharuddin (c) 2 Kapil Dev 3 Srikkanth 4 Sha...,1 Azharuddin (c) 2 Kapil Dev 3 Srikkanth 4 Sha...,NaN

In [8]:
df1[23]

,vteRecipients of Khel Ratna,vteRecipients of Khel Ratna.1
0,1991–2000,Viswanathan Anand (1991–1992) Geet Sethi (1992...
1,2001–2010,Abhinav Bindra (2001) K. M. Beenamol and Anjal...
2,2011–2020,Gagan Narang (2011) Vijay Kumar and Yogeshwar ...
3,2021–2030,"Avani Lekhara, Neeraj Chopra, Ravi Kumar Dahiy..."